Hw2 pull request
Varyzgin/java-tf pull request #2
Opened 2023-10-22 13:15 UTC by Varyzgin

2023-10-22 15:31 UTC, merged

2023-10-23 16:35 UTC, ZhekTheDark requested changes

2023-10-23 16:35 UTC, ZhekTheDark commented on src/main/java/edu/hw2/task1/Expr.java
> +        public double evaluate() {
лучше использовать `Math.pow`

2023-10-23 16:35 UTC, ZhekTheDark commented on src/main/java/edu/hw2/task3/FaultyConnection.java
> +//        if (ThreadLocalRandom.current().nextInt(0, 1) == 1) {1
закоменченый код не пушим

2023-10-23 16:35 UTC, ZhekTheDark commented on src/main/java/edu/hw2/task3/DefaultConnectionManager.java
> +        return ThreadLocalRandom.current().nextInt(0, 2) == 1 ? new FaultyConnection() : new StableConnection();
а почему не `Random().nextInt()`?

2023-10-23 16:35 UTC, ZhekTheDark commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +                manager.getConnection().execute(command);
нужны закрывать конект, давай заюзаем тут try-with-resources

2023-10-24 05:46 UTC, Varyzgin commented on src/main/java/edu/hw2/task3/DefaultConnectionManager.java
> +        return ThreadLocalRandom.current().nextInt(0, 2) == 1 ? new FaultyConnection() : new StableConnection();
Ну тут я пытался выполнить условие, что соединение по умолчанию «иногда» дает сбой (то есть в 1/3 случаев рандома), а так является обычным соединением (когда выпадает 0 или 2)

2023-10-24 05:47 UTC, Varyzgin commented on src/main/java/edu/hw2/task3/FaultyConnection.java
> +//        if (ThreadLocalRandom.current().nextInt(0, 1) == 1) {1
Ок, удалю, но я не понял, это значит, нужно делать новый PR?

2023-10-24 05:47 UTC, Varyzgin commented on src/main/java/edu/hw2/task1/Expr.java
> +        public double evaluate() {
Ладно, поправлю